// controller.ts - Main plugin controller
import { Text3DConfig, PluginMessage, UIMessage, Preset, DEFAULT_CONFIG } from './types';
import { generate3DText } from './generator';
import { detectSelection } from './detector';

const PRESETS_KEY = 'text-3d-presets';

figma.showUI(__html__, { width: 400, height: 600, themeColors: true });

// On plugin start, detect selection
const detection = detectSelection();

if (detection.type === 'plugin-generated') {
  // Load existing config
  const message: UIMessage = {
    type: 'config-loaded',
    config: detection.config!,
    isExisting: true
  };
  figma.ui.postMessage(message);
} else if (detection.type === 'looks-like-3d') {
  // Notify UI that it looks like 3D text but not plugin-generated
  const message: UIMessage = {
    type: 'config-loaded',
    config: DEFAULT_CONFIG,
    isExisting: false
  };
  figma.ui.postMessage(message);
  
  figma.notify('This looks like 3D text, but was not generated by this plugin. You can generate new text or modify manually.');
} else {
  // Load default config
  const message: UIMessage = {
    type: 'config-loaded',
    config: DEFAULT_CONFIG,
    isExisting: false
  };
  figma.ui.postMessage(message);
}

// Load presets
loadPresets();

figma.ui.onmessage = async (msg: PluginMessage) => {
  try {
    switch (msg.type) {
      case 'generate':
      case 'update':
        await handleGenerate(msg.config!);
        break;
        
      case 'save-preset':
        await handleSavePreset(msg.preset!);
        break;
        
      case 'load-preset':
        await handleLoadPreset(msg.presetId!);
        break;
        
      case 'delete-preset':
        await handleDeletePreset(msg.presetId!);
        break;
        
      case 'get-presets':
        await loadPresets();
        break;
    }
  } catch (error) {
    const message: UIMessage = {
      type: 'error',
      error: error instanceof Error ? error.message : 'Unknown error occurred'
    };
    figma.ui.postMessage(message);
  }
};

async function handleGenerate(config: Text3DConfig): Promise<void> {
  // Check if we're updating existing
  const detection = detectSelection();
  const existingNode = detection.type === 'plugin-generated' ? detection.node : undefined;
  
  await generate3DText(config, existingNode);
  
  const message: UIMessage = {
    type: 'generation-complete'
  };
  figma.ui.postMessage(message);
  
  figma.notify(existingNode ? 'Text updated!' : 'Text generated!');
}

async function handleSavePreset(preset: Preset): Promise<void> {
  const presetsJson = await figma.clientStorage.getAsync(PRESETS_KEY);
  let presets: Preset[] = presetsJson ? JSON.parse(presetsJson) : [];
  
  // Check if preset with same ID exists
  const existingIndex = presets.findIndex(p => p.id === preset.id);
  if (existingIndex >= 0) {
    presets[existingIndex] = preset;
  } else {
    presets.push(preset);
  }
  
  await figma.clientStorage.setAsync(PRESETS_KEY, JSON.stringify(presets));
  
  figma.notify(`Preset "${preset.name}" saved!`);
  await loadPresets();
}

async function handleLoadPreset(presetId: string): Promise<void> {
  const presetsJson = await figma.clientStorage.getAsync(PRESETS_KEY);
  if (!presetsJson) return;
  
  const presets: Preset[] = JSON.parse(presetsJson);
  const preset = presets.find(p => p.id === presetId);
  
  if (preset) {
    const message: UIMessage = {
      type: 'config-loaded',
      config: preset.config,
      isExisting: false
    };
    figma.ui.postMessage(message);
    figma.notify(`Preset "${preset.name}" loaded!`);
  }
}

async function handleDeletePreset(presetId: string): Promise<void> {
  const presetsJson = await figma.clientStorage.getAsync(PRESETS_KEY);
  if (!presetsJson) return;
  
  let presets: Preset[] = JSON.parse(presetsJson);
  presets = presets.filter(p => p.id !== presetId);
  
  await figma.clientStorage.setAsync(PRESETS_KEY, JSON.stringify(presets));
  
  figma.notify('Preset deleted!');
  await loadPresets();
}

async function loadPresets(): Promise<void> {
  const presetsJson = await figma.clientStorage.getAsync(PRESETS_KEY);
  const presets: Preset[] = presetsJson ? JSON.parse(presetsJson) : [];
  
  const message: UIMessage = {
    type: 'presets-loaded',
    presets
  };
  figma.ui.postMessage(message);
}